### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by cuiHL** [derekjgriffith/matlab-modtran-5#61]
Method 'ProcessTp7' was not defined for the class 'MODTRANCase' or the method was removed from MATLAB's search path.

**Comment by derekjgriffith** [comment]
MODTRANCase was the name of the MODTRAN 4 wrapper. Do you perhaps have both wrappers installed? Please provide information on the version of Matlab you are using and the context of the error.

**Comment by derekjgriffith** [comment]
Have not received any feedback. Presumed resolved.

**Comment by kosger** [comment]
Hello,

I have this problem, with the MODTRAN 4 wrapper. I use Matlab R2020a prerelease use. I did not have Mod5 installed.

Why would this problem occur?
